### PR TITLE
Fix/ecs alf configs

### PR DESCRIPTION
**Pull request by pete-j-g**
Ticket: https://dsdmoj.atlassian.net/browse/NIT-1
Series of changes to update and clean up the configuration of the ECS implementation of Alfresco. Memory, path and version changes have been tested in alfresco-dev

### CODE REVIEW

**Comment by adeweetman-al** [comment]
Cheers @pete-j-g . Pls can you add some brief context to the PR and some tie back to the relevant ticket?

The code looks good and tidier, just because I'm less close it I need to make some assumptions about the population of those environment variables - not where the values are coming from but know you do!

**Comment by pete-j-g** [comment]
Will update initial comment with more details soon. Tie back to relevant tickets was done through commit messages, but I'll get that clarified too

**Comment by adeweetman-al** [comment]
Ah yes true, didn't see those specific commit messages.

**Review by adeweetman-al — APPROVED** [review]
yep, looks good. thanks.

**Pull request merged**
